name: release

on:
  release:
    types:
      - published
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build artifacts
        run: ./gradlew clean build

      - name: Upload assets to GitHub, Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: IxUlAAFe
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 401859
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          loaders: |
            fabric
            quilt